@echo off
REM Clear all makefile variables that might be used

SET USE_TNT=
SET USE_X32=
SET USE_X32VM=
SET USE_WIN16=
SET USE_WIN32=
SET USE_WIN386=
SET WIN32_GUI=
SET USE_OS216=
SET USE_OS232=
SET USE_OS2GUI=
SET USE_SNAP=
SET USE_SNAP_DRV=
SET USE_QNX4=
SET USE_LINUX=
SET USE_VXD=
SET USE_NTDRV=
SET USE_WINCE=
SET USE_RTTARGET=
SET MAKE_MODE=
SET USE_SMX32=
SET USE_SMX16=
SET USE_DPMI16=
SET USE_LIB_PATH=%LIB%
SET UNIX_TARGET=
