/******************************************************************************
File:      err.h
Version:   2.21
Tab stops: every 2 columns
Project:   any STK related code
Copyright: 1994-1995 DiamondWare, Ltd.  All rights reserved.*
Written:   Keith Weiner & Erik Lorenzen
Purpose:   contains a routine to handle any error generated by the STK
History:   see err.c

Notes
-----
*Permission is expressely granted to use err_Display or any derivitive made
 from it to registered users of the STK.
******************************************************************************/



#ifndef err_INCLUDE

  #define err_INCLUDE



  #include "dosstk.h"
  #include "dwdsp.h"



  /* The following are the modules used by err_Display */
  typedef enum
  {
    err_DWS,
    err_DWDSP

  } err_MODULE;



  #ifdef __cplusplus
    extern "C" {
  #endif



  void err_Display(word errornum, err_MODULE module);



  #ifdef __cplusplus
    }
  #endif



#endif
